### ISSUE TITLE
Anaconda package page for this package is showing "Forbidden"

### ISSUE THREAD

**Issue by oxydaemon** [conda-forge/channels-feedstock#7]
- [X ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue: Anaconda package page for this package is showing "Forbidden"

When you go to: https://anaconda.org/conda-forge/channels

Currently it is showing "You don't have permission to view this page."

Expected: a package listing of current and old versions of files

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by chrisbarber** [comment]
https://github.com/ContinuumIO/anaconda-issues/issues/11750
